### ISSUE TITLE
Плюси і мінуси Counting sort

### ISSUE THREAD

**Issue by kokosik3211** [kokosik3211/Sorting-algorithms#4]

**Comment by bodik16** [comment]
# **_Counting sort is best of the best;_**

**Comment by MaryZ01** [comment]
Неа, насправді InsertionSort таки покраще буде.

**Comment by MaryZ01** [comment]
Ну та насправді, подумайте! Він простий в реалізації і досить швидкий і дієвий для невеликих масивів.

**Comment by MaryZ01** [comment]
Ну ок,(( піду вчити той ваш CoutingSort. ((-__-
